### ISSUE TITLE
Unable to find 'LineChartData' in Demo Code

### ISSUE THREAD

**Issue by UncleRic** [willdale/SwiftUICharts#1]
I couldn't get once scenario to compile due to missing 'LineChartData'.
```
                Section(header: Text("Line Chart")) {
//                    NavigationLink(destination: LineChartDemoView()) {
//                        Text("Line Chart - Week")
//                    }
```

**Comment by willdale** [comment]
Hey, sorry about that! I got a commit out of sync. In the demo there is a new branch called main-1.0.5 that is working.

**Comment by willdale** [comment]
I've updated the link in the project to route to the working branch.
