### ISSUE TITLE
Chart height inconsistencies & labels not appearing

### ISSUE THREAD

**Issue by LJNIC** [willdale/SwiftUICharts#100]
I have multiple views where I swap out the chart data to show different periods of the same data. For the most part, this works fine, but I have run into two issues. First, the height of bar charts is sometimes halved. The only thing changing here is the chart data. 

Normal height:
![image](https://user-images.githubusercontent.com/32738636/124488021-c165df80-dd85-11eb-9725-ceca34db78c7.png)

Halved height:
![image](https://user-images.githubusercontent.com/32738636/124488087-d6427300-dd85-11eb-93bb-38d965f706fb.png)

As can also be seen in the images, the X labels do not appear. They only seem to appear when the graph is not halved, and if the selected data was the initially selected one.

[Here](https://gist.github.com/LJNIC/156e9dbb9919d34c001a02fa9537b411) is some relevant code. `period` is attached to a `@State` variable and changed by a picker.

**Comment by willdale** [comment]
One thing to try would be adding `.id()` modifier to the view.

```swift

.id(chartData.id)

// OR

.id(UUID())

```

**Comment by LJNIC** [comment]
That did it! Thanks a ton.
