### ISSUE TITLE
 xAxisNumberOfLabels for BarChartStyle?

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#101]
Is there no xAxisNumberOfLabels for BarChartStyle? If not any work around? I have a Bar Chart with 60 data points but only want 5 labels so they can fit.

Thanks!

**Comment by willdale** [comment]
There are two options:

1. Don't add the `xAxisLabel` for all but 5 of them, the labels remaining should line up with the correct data point.
1. Set `xAxisLabelsFrom` to '.chartData()', then add the labels you want to `BarChartData -> xAxisLabels`.
