### ISSUE TITLE
Is any way to set pointMarkers customized color or icon?

### ISSUE THREAD

**Issue by wyk111wyk** [willdale/SwiftUICharts#110]
![MultiLineChart](https://user-images.githubusercontent.com/8171481/129825836-ddf4c4c4-4cbd-4b53-9c4f-5fe8efa2f755.png)
Like this one as an example, there are different types of pointMarkers on the lines. But in code I only find a modifier ".pointMarkers", is any way I can set the largest point a special color and the mini one another?

**Comment by willdale** [comment]
Hi, 

There are four different shapes in `pointShape` -->`pointStyle: PointStyle(pointType: .outline, pointShape: .circle)`

You can override individual point colours in the datapoint.
