### ISSUE TITLE
OutLineDataPointExtraLineView causing a huge performance impact

### ISSUE THREAD

**Issue by hahmed1** [willdale/SwiftUICharts#124]
First of off thanks for this project, I like it a lot.  

I have recently run into an issue where loading a View takes an abnormally long time (like 4-5 seconds delay).

I profiled my application using the SwiftUI tool in Instruments and was able to narrow down the issue to the OutLineDataPointExtraLineView struct:

![image](https://user-images.githubusercontent.com/4490697/136667949-a7b5ece9-0674-4bb5-9af8-69ab590d837a.png)

The columns in the table are Module / View Type, Count, Total Duration, Min Duration, Avg. Duration, and Max Duration.

For a bit of context, the chart is rendering a LineView with an extra line, and there are about 1000 data points in each line (is this a reasonable amount of data? I don't see anything in the docs about what is reasonable). 

What is really weird about this is that it only became an issue after adding Firebase Analytics to the app.  Here is a profile of rendering the same view without Firebase in the project: 

![image](https://user-images.githubusercontent.com/4490697/136668671-f19b3e10-ab75-41d1-937f-ef36a314009b.png)

What I'd like to know is: 

- Is there any stress testing / benchmarking to see what is a reasonable amount of data to render 
- Any clues as how the addition of another third party library (Firebase Analytics) to a totally unrelated section of the app could cause OutLineDataPointExtraLineView to be rendered so many times and with such poor render times ( I realize it is unreasonable to expect an answer to this one, but any hints to help drive my investigation would be appreciated)

**Comment by willdale** [comment]
Hey @hahmed1, I can't think what Firebase Analytics might be doing to `OutLineDataPointExtraLineView`.

One thing to try adding `.drawingGroup()` to the end of the declaration. [drawingGroup(opaque:colorMode:)
](https://developer.apple.com/documentation/swiftui/view/drawinggroup(opaque:colormode:))

1000 data points should be fine, I have no specific metrics for how many is too many.

**Comment by paulz** [comment]
we are also seeing this performance hit and `.drawingGroup()` did not help immediately

```
#8	0x0000000104c0bcb4 in ExtraLineData.getMaxValue() at checkouts/SwiftUICharts/Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineData.swift:116
#9	0x0000000104c0b9d4 in ExtraLineData.range.getter at checkouts/SwiftUICharts/Sources/SwiftUICharts/SharedLineAndBar/Models/ExtraLineData.swift:81
#10	0x0000000104c8753c in OutLineDataPointExtraLineView.body.getter at checkouts/SwiftUICharts/Sources/SwiftUICharts/SharedLineAndBar/ViewModifiers/ExtraLine.swift:515

```

looks like 
```
    internal func getMaxValue() -> Double {
        self.dataPoints
            .map(\.value)
            .max() ?? 0
    }
```
is slow on device (not simulator) when we have 1000 points
