### ISSUE TITLE
Bar Chart: Negative values below the X-axis

### ISSUE THREAD

**Issue by ahartman** [willdale/SwiftUICharts#126]
Beautiful library. However, it seems to suffer from an issue that many charting libraries have.
Bar graphs cannot have negative va:lues, i.e., below the X-axis. For me that is an requirement.

Regards, ahartman, belgium

**Comment by willdale** [comment]
I'll look into it. It's won't be for a while.

**Comment by ahartman** [comment]
I must correct myself. All bar charts correctly display negative values except the stacked bar chart.
Naturally, it is the stacked bar chart that I need!

Please see example below.
Regards, ahartman, belgium

<img width="769" alt="Schermafbeelding 2021-11-25 om 09 11 58" src="https://user-images.githubusercontent.com/688316/143403960-5bdf22e4-22d6-4279-9ea5-b417fd4e3eac.png">

**Comment by willdale** [comment]
Thanks to [kunalverma25](https://github.com/kunalverma25). This is fixed in v2.9.8.
