### ISSUE TITLE
Is there currently a way to ignore 0 for an Extra Line? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#133]
I couldn't figure out a way presently to ignore 0 on an extra line in a LineChart.  I know that `ignoreZore` is an option on `LineStyle` but isn't on `ExtraLineStyle`, is there any other work around?  Otherwise my chart looks like the below:  (blue is the extraLine data.  
![IMG_220FF8EF1DA1-1](https://user-images.githubusercontent.com/9816100/140997369-6c7452c8-b081-4523-84e3-fae058b02a19.jpeg)

**Comment by gesabo** [comment]
I ended up just switching to a MultiLineChart which works well and enables me to ignore zeros so probably not something that is necessary.  👍

**Comment by pinventado** [comment]
I'm also using a MultiLineChart with ignorezero to hide some data points. However, it seems like the baseLine is set to 0 even though I don't have points that are zero. I'm assuming this is because there is a data point that's zero, but just hidden. Unless I'm missing something?

**Comment by willdale** [comment]
Hey @gesabo, I'll look at adding the feature to extra line in v3.

**Comment by willdale** [comment]
Hey @pinventado, it has been fixed in V2.9.5.
