### ISSUE TITLE
FATAL ERROR at orientation change

### ISSUE THREAD

**Issue by ahartman** [willdale/SwiftUICharts#143]
I have two graphs, a multi-line chart and a stacked bar chart; both display an extraLine.
When using GeometryReader for the frame size, the app crashes at an orientation change; with fixed numbers for frame size redrawing is ok.
Please see below:
1. code for the view
2. error message from Xcode
3. code where the crash occurs
<img width="883" alt="Schermafbeelding 2021-11-29 om 11 26 04" src="https://user-images.githubusercontent.com/688316/143853004-1ecbbe08-c845-4dfc-9af4-195030f6d37f.png">

<img width="936" alt="Schermafbeelding 2021-11-29 om 11 25 32" src="https://user-images.githubusercontent.com/688316/143853098-110f40e5-515c-4b68-b3e2-0afc6b857479.png">

<img width="897" alt="Schermafbeelding 2021-11-29 om 11 31 25" src="https://user-images.githubusercontent.com/688316/143853123-b5b0a809-8560-4a3c-83c3-10791ad39f99.png">

**Comment by willdale** [comment]
While couldn't replicate the fatal error, I did find a potential issue in that area.

There is a fix for that in v2.9.6

---

Looking at your view, my suggestion would be to:
- Put the `GeometryReader` inside the `NavigationView`
- Add `.id(data.id)` the the view after `.legends()
- Move everything from `StackedBarChart` to `id()` into a sub view.
