### ISSUE TITLE
Negative Values going out of frame/bounds (BarCharts)

### ISSUE THREAD

**Issue by kunalverma25** [willdale/SwiftUICharts#148]
For both Horizontal and vertical bar charts, negative value bars are drawn out of the frame.
If the horizontal chart is full width or vertical chart is full height then negative bars will be drawn out of the screen.

Eg -
![Screenshot 2021-12-16 at 11 10 05 AM](https://user-images.githubusercontent.com/5118260/146314908-8ab44f26-5ebf-47b3-b96c-d513504392d8.png)

**Comment by kunalverma25** [comment]
This is because of scaleEffect doesn't change the frame.
Any idea how to fix this?

**Comment by kunalverma25** [comment]
@willdale Any fix for this?

**Comment by kunalverma25** [comment]
Even with baseline set properly, the bar chart does not respect that and starts drawing only from the baseline itself.

![Screenshot 2021-12-24 at 10 39 32 AM](https://user-images.githubusercontent.com/5118260/147319093-0180d57f-0b20-4717-b115-e32071b7a9d8.png)

**Comment by willdale** [comment]
I'll look in to this in V3

**Comment by willdale** [comment]
Thanks for your PR.
