### ISSUE TITLE
Corner radius not correct for horizontal bars with smaller values

### ISSUE THREAD

**Issue by sai-manoj-kumar** [willdale/SwiftUICharts#178]
Due to the scaleEffect on the xAxis in the HorizontalColourBar the smaller bars are not rounded properly.
Please note the difference in underlined bars.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/647333/159291742-fb686b8e-f450-46af-b8ff-50cd1ee6b897.png">

**Comment by willdale** [comment]
Hey @sai-manoj-kumar, just linking this to an existing issue: #58. I'll review your PR.
