### ISSUE TITLE
Animations animating twice? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#182]
I love the animations of this library but I've noticed sometimes they animate twice or more.  I'm sure it's related to the data I'm loading and the views withdrawing but wondering if there are any tips or advice to prevent it from animating multiple times? 🤔

**Comment by willdale** [comment]
Hey @gesabo, can you post some minimum reproducible code please? There can be multiple reasons why this can happen. 

One option could be to add `.id()` to the end of chain of functions, you may already have this, or maybe put the chart in a sub view - see: #139.

**Comment by gesabo** [comment]
@willdale thanks! Yes already knew to use `.id()` but will try nesting in a subview as well.  I don't think it has to do with the chart itself, it's probably related to my data publishers firing multiple times. 👍
