### ISSUE TITLE
X labels height is miscalculated

### ISSUE THREAD

**Issue by AvdLee** [willdale/SwiftUICharts#185]
Looking at this code:

https://github.com/willdale/SwiftUICharts/blob/7b50b531c36f30d41b5208f7dbc63df245936849/Sources/SwiftUICharts/SharedLineAndBar/Views/RotatedText.swift#L58

Shouldn't we add the height to the `xAxisLabelHeights` instead of the width?

**Comment by willdale** [comment]
Hey @AvdLee, you beat me to my mornings' task.

**Comment by AvdLee** [comment]
That was fast, thanks a lot! Closing this one accordingly.
