### ISSUE TITLE
How to remove xAxis and yAxis lines? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#197]
Even without a grid or setting the gridlines to .clear, I can't seem to find a way to remove the thin xAxis and xAxis lines here, is there a way? 🤔 

![image](https://user-images.githubusercontent.com/9816100/166821594-08dec246-56ce-429e-bdb0-d2b89d466634.png)

**Comment by willdale** [comment]
Hey @gesabo, set 
```swift
LineChartStyle(...,
    xAxisBorderColour: nil,
    yAxisBorderColour: nil,
    ....
```

**Comment by gesabo** [comment]
Thank you! 🙏

**Comment by gesabo** [comment]
@willdale for my use case I actually wanted to to keep the X and Y Axis labels for purposes of preserving space and setting their text color as `.clear` (I was trying to overlay 1 chart over another chart), and I found that these lines wouldn't be removed unless I removed, e.g. `.xAxisLabels(chartData: data)`.  I understand this is sort of "off label" use (bad pun 😆 ) but would be nice if ever possible.

**Comment by gregorpichler** [comment]
I agree with @gesabo, it would be great if we could remove the line but still have the labels (xAxis and/or yAxis). If I set `xAxisBorderColour: nil` it only works if I remove `.xAxisLabels(chartData: data)`. Am I missing something here @willdale?
