### ISSUE TITLE
How can I have solid horizontal grid lines

### ISSUE THREAD

**Issue by Ale111** [willdale/SwiftUICharts#204]
I'm trying to create a StackedBarChart with an horizontal solid lines grid, but I have not found a way to do this. I don't know where I'm missing.

Here is the end of my makedata() 

`      
let yAxisGridStyle = GridStyle(
                    numberOfLines: 7,
                    lineColour: Color.black,
                    lineWidth: 1,
                    dash: [1000]
                )

        return StackedBarChartData(dataSets: data,
               groups: groups,
               barStyle: BarStyle(barWidth: 0.5),
               chartStyle: BarChartStyle(infoBoxPlacement: .header,
                                         xAxisGridStyle: yAxisGridStyle,
                                         xAxisLabelsFrom: .dataPoint(rotation: .degrees(0)),
//                                         yAxisGridStyle: yAxisGridStyle,
                                         yAxisNumberOfLabels: 7,
                                         yAxisLabelType: .numeric,
                                         baseline: .zero,
                                         topLine: .maximum(of:  costi.totale)))
`

And here there is the result, as well, uncomment the line "yAxisGridStyle: yAxisGridStyle," has no effect on drawing horizontal grid. I need to have Horizontal lines grid only instead of verticals. 

![Simulator Screen Shot - iPhone 8 - 2022-05-27 at 17 29 26](https://user-images.githubusercontent.com/9302237/170733153-c0fe9d15-12e1-42b0-93ed-4392a02e041a.png)

Thanks in advance for the help!

**Comment by willdale** [comment]
Hi, are you using `yAxisGrid` or `xAxisGrid` in the view?

```swift
StackedBarChart(chartData: data)
    .yAxisGrid(chartData: data)
```

```swift
yAxisGridStyle: GridStyle(numberOfLines: 5,
                          lineColour: Color.gray.opacity(0.25),
                          dash: []),
```

**Comment by Ale111** [comment]
Yeap.. I was missing .yAxisGrid... my fault. 
Thank you a lot.
Work fine now! 
![Simulator Screen Shot - iPhone 8 - 2022-05-27 at 20 21 47](https://user-images.githubusercontent.com/9302237/170769078-f1a87965-60c9-4021-9081-10a8de58b374.png)
