### ISSUE TITLE
Modify text style on legend, labels etc..

### ISSUE THREAD

**Issue by OguzYuuksel** [willdale/SwiftUICharts#21]
If labels, legends or other string values can be modified on view layer, not the data model layer. Users may have ability to modify chart view to adapt their screen.
Also when I wanted to add price unit, near my touch overlay data but in this structure it is not easy. 
I think there may be some improvements to move some properties to view layer and have a simple data model layer.

**Comment by willdale** [comment]
I've add units to the touch overlay, it's in the latest release - version 1.1.3.

## Example
```swift
.touchOverlay(units: .prefix(of: "USD"))
// OR
.touchOverlay(units: .suffix(of: "USD"))
```

I'll have a look and a think about the view layer vs model layer.

**Comment by OguzYuuksel** [comment]
Thank you! This is the most useful SwiftUI charts lib among others. When I have free time I will try to understand source codes and think if I can contribute in someway.

**Comment by willdale** [comment]
No worries! Glad you find it useful. Any contributions would be appreciated.

## View Layer vs Model Layer

The model can be updated from the view. If your xAxisLabels in data model are:

---

```swift 
["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"]
```
But you want to change them you can change them on the fly by:
```swift
.onAppear {
    data.xAxisLabels = ["Jan", "Dec"]
}
```
---

I've just added another version 1.1.4 that fixes a small bug and now exposes the `ChartMetaData` to the api. This allows you to up date those value on the fly.
```swift
.onChange(of: someValue, perform: { _ in
    data.metadata?.title = "A new title"
    data.metadata?.subtitle = "A new subtitle"
})
```

---
## Version 2

I'm working on a [version 2](https://github.com/willdale/SwiftUICharts/tree/version-2) at the moment to add some new features and chart types. The hope is that version 2 will be easier to add new chart types without loads of duplicated code.
