### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by owenzhao** [willdale/SwiftUICharts#226]
After upgrading to Ventura, I got this purple alert a lot. Xcode 14.1 RC2.

<img width="2160" alt="截屏2022-10-30 07 31 15" src="https://user-images.githubusercontent.com/2182896/198856266-599ce974-7355-43db-b8e9-8242f973a2f3.png">

SwiftUICharts 2.10.0.

**Comment by longvudai** [comment]
<img width="1864" alt="Screenshot 2022-10-30 at 11 37 13" src="https://user-images.githubusercontent.com/32995348/198862817-6316f7d5-c940-4cfd-a962-1f1fb6629f9a.png">

I have the same problem

**Comment by mehroozkhan** [comment]
same here.

**Comment by gesabo** [comment]
same issue, however I am noticing that simply adding @Environment(\.scenePhase) var scenePhase (not even calling the scenePhase) causes the error, if I remove it, no error.  Might this help @willdale ?

**Comment by MehdiAbdi** [comment]
I have the same issue.

**Comment by Arangott** [comment]
I am also facing this issue. Getting more than 200 warnings.
<img width="1036" alt="Screenshot 2023-02-28 at 12 13 00" src="https://user-images.githubusercontent.com/114466254/221744218-9a7c36c6-86f2-4a0e-9850-cb1b32572943.png">
