### ISSUE TITLE
X-Axis labels truncate

### ISSUE THREAD

**Issue by geeklingo** [willdale/SwiftUICharts#27]
The label text truncates, makes it a little harder to read at a glance as users would have to tap each bar to see the full text. Would be great to have an option to display X-axis labels rotated at n-degrees and showing full text (no truncating)

**Comment by willdale** [comment]
This is fixed in version 2. I hope to have it out within a week.

![Image of Bar Chart](https://raw.githubusercontent.com/willdale/SwiftUICharts/version-2/Resources/images/BarCharts/BarChart.png)

[Version 2 ReadMe](https://github.com/willdale/SwiftUICharts/tree/version-2#swiftuicharts)

**Comment by willdale** [comment]
Version 2 is released including the fix.

**Comment by geeklingo** [comment]
Nice thanks

**Comment by geeklingo** [comment]
Can we please get this on the other bar charts as well? E.g. stacked

**Comment by willdale** [comment]
Fixed in v2.1.0.

**Comment by geeklingo** [comment]
> Fixed in v2.1.0.

Is there anything special I need to add to have it rotate 90 degrees on stacked? I get overlapping axis labels on stacked. Running 2.1.0.

**Comment by willdale** [comment]
Can you send a screenshot?

**Comment by geeklingo** [comment]
![IMG_E32B4524AFC1-1](https://user-images.githubusercontent.com/36504208/112056958-67f5ee00-8ba4-11eb-9fd4-0d10f3fa5a70.jpeg)

**Comment by geeklingo** [comment]
Maybe a value like `xAxisRotation: <val>` in the return so the rotation can be custom?

**Comment by willdale** [comment]
`xAxisLabelsFrom: .dataPoint(rotation: .degrees(90))`

You have it set to zero. Could that be it?

**Comment by willdale** [comment]
<img width="1441" alt="Screenshot 2021-03-22 at 21 06 03" src="https://user-images.githubusercontent.com/63838770/112058436-803d1d00-8b52-11eb-8c4c-c2e5f6a9c114.png">

**Comment by geeklingo** [comment]
Oh man, sorry, not sure how I missed that.

**Comment by willdale** [comment]
No worries, glad its sorted.
