### ISSUE TITLE
Chart in ScrollView - Cannot initiate scroll from chart

### ISSUE THREAD

**Issue by mgauthier** [willdale/SwiftUICharts#30]
When I add a line chart with the touchoverlay enabled into a scrollview, I find that I can only scroll when I start the scroll gesture outside of the chart. Is this expected behavior?

**Comment by willdale** [comment]
That is as I would expect, I can't think of a way to differentiate between the two touch instructions.

**Comment by willdale** [comment]
The only implementation I can get to work is a `Button` in the `ScrollView` that turns on the `DragGesture` in `.touchOverlay`. 

It's not the prettiest way of doing it but it would somewhat allow for what you want.

https://user-images.githubusercontent.com/63838770/111297601-b1df5100-8645-11eb-8afe-bbf39ef25163.mov

Let me know if you want this implemented or if you can think of a different way of doing it.

**Comment by mgauthier** [comment]
Interesting, I'm curious to see the video, but I'm having trouble playing it

**Comment by willdale** [comment]
No idea why you can't play it but here's a [link to a YouTube version](https://www.youtube.com/watch?v=uR8EN8qQ8HQ)

**Comment by willdale** [comment]
Feel free to come back to this.

**Comment by willdale** [comment]
@krin-san you are a star! Sorry it took a while to look at this. I'll add it to the next release.

**Comment by willdale** [comment]
This is now possible in v2.8.

```swift
.touchOverlay(chartData: data, specifier: "%.0f", minDistance: 10)
```
---
 Will
