### ISSUE TITLE
Legend not showing all values on stacked bar chart

### ISSUE THREAD

**Issue by geeklingo** [willdale/SwiftUICharts#34]
I have a chart where i stack 5 different values. On the demo app, I can see all 3 legends being displayed on the graph (England, Wales & Scotland). But when I try to adapt to my data, I can only show 2 of the 5 in the legend.

Note: This is the legend only, the stacked graph is showing all 5 correctly.

**Comment by geeklingo** [comment]
Actually, maybe because I'm not setting the legendTag?
![image](https://user-images.githubusercontent.com/36504208/111456844-34116780-8763-11eb-9da7-05ed89bcf1ff.png)

**Comment by geeklingo** [comment]
How do we set that attribute (legendtag)? I can't see any reference in the readme to it.

**Comment by willdale** [comment]
The `legendTag` is a way of handling Legends  internally for the touch overlay, I'll see if I can remove it from the public API. 

 The legends for `StackedBarChart` are taken from the `GroupingData`. 

Can you post some code?

**Comment by geeklingo** [comment]
I've got my grouping data like this. It must be working as the charts are showing the correct stacked bars and tapping on the bars is showing the correct group and value. It's just the legend that doesn't seem to be pulling all the values.
The only difference in my code and the demo is that I use a for loop to populate MultiBarChartDataPoint and Sets.

```
            var data : GroupingData {
                switch self {
                case .type1:       return GroupingData(title: "Type 1",    colour: ColourStyle(colour:Color(UIColor.systemGray)))
                case .type2:     return GroupingData(title: "Type 2",  colour: ColourStyle(colour:Color(UIColor.systemGreen)))
                case .type3:      return GroupingData(title: "Type 3",   colour: ColourStyle(colour:Color(UIColor.systemYellow)))
                case .type4:    return GroupingData(title: "Type 4", colour: ColourStyle(colour: Color(UIColor.systemRed)))
                case .type5:    return GroupingData(title: "Type 5", colour: ColourStyle(colour: .primary))
                }
            }
```

**Comment by geeklingo** [comment]
Oh hahahaha nevermind, i'm such an idiot. 
let groups : [GroupingData] = 

I didn't have the full set in there.

**Comment by willdale** [comment]
You got there a second before me.
