### ISSUE TITLE
Feature Request: Ability to filter data

### ISSUE THREAD

**Issue by geeklingo** [willdale/SwiftUICharts#35]
Would be great if we could have a picker or something similar to be able to filter the data set.

**Comment by willdale** [comment]
In the demo app look at `Other -> Filtered Demo`.

Is that what you would like?

**Comment by geeklingo** [comment]
Oh, just noticed that. Yeah something like that but not dates, maybe things like where you can group chunks of data (e.g. all open jobs etc..). I'll take a look at that code a little more.

**Comment by willdale** [comment]
The filtering is handled outside of the charts library. Before the `ChartData` is initialised you can run a `filter` or `predicate` to get the data points you need from your data store.
