### ISSUE TITLE
Feature Request: Table view

### ISSUE THREAD

**Issue by geeklingo** [willdale/SwiftUICharts#36]
Sometimes it's good to display the data table under the graph. Is there a way to achieve this with this library?

**Comment by willdale** [comment]
I don't think that that is something that should be done in the library, I'm not sure how to deal with allowing flexible cell layouts. Could it not be done more easily from outside the library, just hook into the same that builds the data sets?

**Comment by geeklingo** [comment]
Yeah, you are probably right. Thanks, I’ll take a look.

**Comment by willdale** [comment]
I'm open to discussion on it.
