### ISSUE TITLE
Is it possible to make line(bar) chart scrollable horizontally?

### ISSUE THREAD

**Issue by wyk111wyk** [willdale/SwiftUICharts#38]
Sometime the data is really too much  to show.
AND the infobox will be covered by yAxisPOI, as attachment shows
<img width="340" alt="截屏2021-03-23 下午5 27 08" src="https://user-images.githubusercontent.com/8171481/112124305-2c3b4280-8bfd-11eb-828d-53f14e389a89.png">
.

**Comment by willdale** [comment]
Hi,

To make it scrollable, put it in a `ScrollView`.

The order of the `View Modifiers` changes the `zIndex` of the element so if you move the overlay down it should be on top.


https://user-images.githubusercontent.com/63838770/112128302-3558ef00-8bbe-11eb-89a4-bc41022c5a59.mov


```swift
struct LineChartDemoView: View {
    
    let dataOne : LineChartData = weekOfData()
    let dataTwo : LineChartData = weekOfData()
    
    var body: some View {
        
        List {
            Section(header: Text("Chart One")) {
                chartOne
            }
            Section(header: Text("Chart Two")) {
                chartTwo
            }
                
        }
        .listStyle(InsetGroupedListStyle())
        .navigationTitle("Week of Data")
    }
    
    var chartOne: some View {
        ScrollView(.horizontal) {
            LineChart(chartData: dataOne)
                .pointMarkers(chartData: dataOne)
                .touchOverlay(chartData: dataOne, specifier: "%.0f")
                .yAxisPOI(chartData: dataOne,
                          markerName: "Step Count Aim",
                          markerValue: 15_000,
                          labelPosition: .center(specifier: "%.0f"),
                          labelColour: Color.black,
                          labelBackground: Color(red: 1.0, green: 0.75, blue: 0.25),
                          lineColour: Color(red: 1.0, green: 0.75, blue: 0.25),
                          strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .yAxisPOI(chartData: dataOne,
                          markerName: "Minimum Recommended",
                          markerValue: 10_000,
                          labelPosition: .center(specifier: "%.0f"),
                          labelColour: Color.white,
                          labelBackground: Color(red: 0.25, green: 0.75, blue: 1.0),
                          lineColour: Color(red: 0.25, green: 0.75, blue: 1.0),
                          strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .averageLine(chartData: dataOne,
                             strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .xAxisGrid(chartData: dataOne)
                .yAxisGrid(chartData: dataOne)
                .xAxisLabels(chartData: dataOne)
                .yAxisLabels(chartData: dataOne)
                .floatingInfoBox(chartData: dataOne)
                .legends(chartData: dataOne, columns: [GridItem(.flexible()), GridItem(.flexible())])
                .id(dataOne.id)
                .frame(minWidth: 900, idealWidth: 1000, maxWidth: 1100, minHeight: 150, idealHeight: 200, maxHeight: 300)
                .padding(.vertical)
        }
        .padding(.all)
    }
    var chartTwo: some View {
        ScrollView(.horizontal) {
            LineChart(chartData: dataTwo)
                .pointMarkers(chartData: dataTwo)
                .touchOverlay(chartData: dataTwo, specifier: "%.0f")
                .yAxisPOI(chartData: dataTwo,
                          markerName: "Step Count Aim",
                          markerValue: 15_000,
                          labelPosition: .center(specifier: "%.0f"),
                          labelColour: Color.black,
                          labelBackground: Color(red: 1.0, green: 0.75, blue: 0.25),
                          lineColour: Color(red: 1.0, green: 0.75, blue: 0.25),
                          strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .yAxisPOI(chartData: dataTwo,
                          markerName: "Minimum Recommended",
                          markerValue: 10_000,
                          labelPosition: .center(specifier: "%.0f"),
                          labelColour: Color.white,
                          labelBackground: Color(red: 0.25, green: 0.75, blue: 1.0),
                          lineColour: Color(red: 0.25, green: 0.75, blue: 1.0),
                          strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .averageLine(chartData: dataTwo,
                             strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
                .xAxisGrid(chartData: dataTwo)
                .yAxisGrid(chartData: dataTwo)
                .xAxisLabels(chartData: dataTwo)
                .yAxisLabels(chartData: dataTwo)
                .floatingInfoBox(chartData: dataTwo)
                .legends(chartData: dataTwo, columns: [GridItem(.flexible()), GridItem(.flexible())])
                .id(dataTwo.id)
                .frame(minWidth: 900, idealWidth: 1000, maxWidth: 1100, minHeight: 150, idealHeight: 200, maxHeight: 300)
                .padding(.vertical)
        }
        .padding(.all)
    }
    
    static func weekOfData() -> LineChartData {
        let data = LineDataSet(dataPoints: [
            LineChartDataPoint(value: 12000, xAxisLabel: "M", description: "Monday"),
            LineChartDataPoint(value: 10000, xAxisLabel: "T", description: "Tuesday"),
            LineChartDataPoint(value: 8000,  xAxisLabel: "W", description: "Wednesday"),
            LineChartDataPoint(value: 17500, xAxisLabel: "T", description: "Thursday"),
            LineChartDataPoint(value: 16000, xAxisLabel: "F", description: "Friday"),
            LineChartDataPoint(value: 11000, xAxisLabel: "S", description: "Saturday"),
            LineChartDataPoint(value: 9000,  xAxisLabel: "S", description: "Sunday")
        ],
        legendTitle: "Steps",
        pointStyle: PointStyle(),
        style: LineStyle(lineColour: ColourStyle(colour: .red), lineType: .curvedLine))
        

        let gridStyle  = GridStyle(numberOfLines: 7,
                                   lineColour   : Color(.lightGray).opacity(0.5),
                                   lineWidth    : 1,
                                   dash         : [8],
                                   dashPhase    : 0)
        
        let chartStyle = LineChartStyle(infoBoxPlacement    : .floating,
                                        infoBoxBorderColour : Color.primary,
                                        infoBoxBorderStyle  : StrokeStyle(lineWidth: 1),
                                        
                                        markerType          : .vertical(attachment: .line(dot: .style(DotStyle()))),
                                        
                                        xAxisGridStyle      : gridStyle,
                                        xAxisLabelPosition  : .bottom,
                                        xAxisLabelColour    : Color.primary,
                                        xAxisLabelsFrom     : .dataPoint(rotation: .degrees(0)),
                                        
                                        yAxisGridStyle      : gridStyle,
                                        yAxisLabelPosition  : .leading,
                                        yAxisLabelColour    : Color.primary,
                                        yAxisNumberOfLabels : 7,
                                        
                                        baseline            : .minimumWithMaximum(of: 5000),
                                        topLine             : .maximum(of: 20000),
                                        
                                        globalAnimation     : .easeOut(duration: 1))
        
        return LineChartData(dataSets       : data,
                             metadata       : ChartMetadata(title: "Step Count", subtitle: "Over a Week"),
                             chartStyle     : chartStyle)
        
    }
}
```

**Comment by wyk111wyk** [comment]
Is this the power of SwiftUI?

**Comment by willdale** [comment]
I am super enjoying SwiftUI. Particularly after working on a appkit project.

**Comment by wyk111wyk** [comment]
Well, after I put the chart in a scrollView, something went wrong when the line was drawing. Something wrong with height.
<img width="1440" alt="截屏2021-03-23 下午7 26 18" src="https://user-images.githubusercontent.com/8171481/112139666-07030000-8c0e-11eb-807a-76c839facd09.png">

**Comment by willdale** [comment]
Have you got `.id(dataOne.id)` attached to the chart?

If you can, could you post the view code?

**Comment by wyk111wyk** [comment]
Sure.
BTW, how can I use gradient color for FilledLineChart? I didn't find it in demo code.

struct RecordHistoryView: View {
<img width="349" alt="截屏2021-03-23 下午8 00 47" src="https://user-images.githubusercontent.com/8171481/112143159-7844b200-8c12-11eb-8993-31efce82f2c4.png">

    @State private var openRecordHistory: Bool = true
    let data : LineChartData = weekOfData()
    
    var body: some View {
        NavigationView {
            Group {
                if openRecordHistory {
                    Form {
                        Section(header: Text("Odometer - Total range")) {
                            ScrollView(.horizontal) {
                                self.lineChartView
                                    .padding(.vertical)
                            }
                        }
                        Section(header: Text("title")) {
                            self.lineChartView
                                .padding(.vertical)
                        }
                        Section(header: Text("title")) {
                            self.lineChartView
                                .padding(.vertical)
                        }
                    }
                }else {
                    ZStack {
                        ViewHelper().placeholdView(.charts, showTitle: false)
                        VStack {
                            Spacer()
                            self.openButton
                                .padding()
                        }
                    }
                }
            }
            .navigationTitle("Record history")
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}

extension RecordHistoryView {
    var lineChartView: some View {
        FilledLineChart(chartData: data)
//            .headerBox(chartData: data)
//            .pointMarkers(chartData: data)
            .yAxisPOI(chartData: data,
                      markerName: "Step Count Aim",
                      markerValue: 400,
                      labelPosition: .center(specifier: "%.0f"),
                      labelColour: Color.black,
                      labelBackground: Color(red: 1.0, green: 0.75, blue: 0.25, opacity: 0.8),
                      lineColour: Color(red: 1.0, green: 0.75, blue: 0.25),
                      strokeStyle: StrokeStyle(lineWidth: 3, dash: [5,10]))
            .infoBox(chartData: data)
            .touchOverlay(chartData: data, specifier: "%.1f", unit: .suffix(of: "km"))
            .xAxisGrid(chartData: data)
            .yAxisGrid(chartData: data)
            .xAxisLabels(chartData: data)
            .yAxisLabels(chartData: data)
            .legends(chartData: data,
                     columns: [GridItem(.flexible()), GridItem(.flexible())])
            .id(data.id)
            .frame(minWidth: 200, idealWidth: 400, minHeight: 150, idealHeight: 250, maxHeight: 300, alignment: .center)
    }
    
    static func weekOfData() -> LineChartData {
            let data = LineDataSet(dataPoints: [
                LineChartDataPoint(value: 450.3, xAxisLabel: "13400", description: "16933 km"),
                LineChartDataPoint(value: 320.5, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 110.2,  xAxisLabel: "23123", description: "16933 km"),
                LineChartDataPoint(value: 320.4, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 298.23, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 87.12, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 160.74,  xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 400.23, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 289, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 250,  xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 100, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 388, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 287, xAxisLabel: "16933", description: "16933 km"),
                LineChartDataPoint(value: 196,  xAxisLabel: "16933", description: "16933 km")
            ],
            legendTitle: "Battery range",
            pointStyle: PointStyle(),
            style: LineStyle(lineColour: ColourStyle(colour: .green),
                             lineType: .curvedLine))
            
            let metadata   = ChartMetadata(title: "Odometer - Total range", subtitle: "")
            
            let gridStyle  = GridStyle(numberOfLines: 7,
                                       lineColour   : Color(.lightGray).opacity(0.5),
                                       lineWidth    : 0.7,
                                       dash         : [10],
                                       dashPhase    : 0)
            
            let chartStyle = LineChartStyle(infoBoxPlacement    : .infoBox(isStatic: false),
                                            infoBoxBorderColour : Color.primary,
                                            infoBoxBorderStyle  : StrokeStyle(lineWidth: 1),
                                            
//                                            markerType          : .vertical(attachment: .line(dot: .style(DotStyle()))),
                                            markerType          : .indicator(style: DotStyle()),
                                            
                                            xAxisGridStyle      : gridStyle,
                                            xAxisLabelPosition  : .bottom,
                                            xAxisLabelColour    : Color.primary,
                                            xAxisLabelsFrom     : .dataPoint(rotation: .degrees(-40)),
                                            
                                            yAxisGridStyle      : gridStyle,
                                            yAxisLabelPosition  : .leading,
                                            yAxisLabelColour    : Color.primary,
                                            yAxisNumberOfLabels : 6,
                                            
                                            baseline            : .zero,
                                            topLine             : .maximum(of: 500),
                                            
                                            globalAnimation     : .easeOut(duration: 1))
            
            return LineChartData(dataSets       : data,
                                 metadata       : metadata,
                                 chartStyle     : chartStyle)
            
        }
    
}

**Comment by willdale** [comment]
```swift
//            .infoBox(chartData: data)            // <--- Replace
            .floatingInfoBox(chartData: data) // <--- With
```

```swift
// .infoBox(isStatic: false)             // <--- Replace
   .infoBoxPlacement    : .floating // <--- With
```

**Comment by willdale** [comment]
# Colour
```swift
LineDataSet(...
style: LineStyle(lineColour: ColourStyle(colours: [Color.red, Color.blue], startPoint: .top, endPoint: .bottom),
```

**Comment by wyk111wyk** [comment]
Thx, It works. 
But well, the floatingInfoBox used too much space, can you fix the staticInfoBox?

**Comment by willdale** [comment]
I missed the modifier order: move the `.infoBox(chartData: data)` to the bottom.

**Comment by willdale** [comment]
Found a bug,. Fix soon.

**Comment by willdale** [comment]
`.floatingInfoBox()` size fixed in v2.1.1.

**Comment by USBA** [comment]
> `.floatingInfoBox()` size fixed in v2.1.1.

I was about to open an issue for this. Thanks @willdale, you're a treasure for the entire SwiftUI community.

**Comment by wyk111wyk** [comment]
I can say this is the best Chart library by SwiftUI now, thx willdale.

**Comment by willdale** [comment]
@USBA Glad everything is working for you and thank you for the kind words.

@wyk111wyk Wonderful, let me know if you come across any other issues.

**Comment by wyk111wyk** [comment]
Hi, I'm coming again~
Is it possible to add the trend line for lineChart?

**Comment by willdale** [comment]
Could you open another issue for it please.

**Comment by kunalverma25** [comment]
Will it be possible to have the Y-Axis Legends/Tags not scrollable, but rest of the chart scrollable?

**Comment by AakashGeidea** [comment]
Hi @willdale, firstly would like to congratulate you for making this absolute useful library. I used this in one of my project and facing issue with scrolling direction for RTL (for arabic language). Could you please guide or provide me some sample code for this horizontal scrolling for RTL langauge?
