### ISSUE TITLE
Is it possible to add the trend line for lineChart

### ISSUE THREAD

**Issue by wyk111wyk** [willdale/SwiftUICharts#39]
This is be a very useful feature for chart

**Comment by willdale** [comment]
Would using a `MultiLineChart` do the trick?

There are different ways of calculating a trend line depending on what you're doing.

How would you like to be able to use it? ie from the perspective of initialization.

**Comment by wyk111wyk** [comment]
I'm make an EV management software, so I'd like to demonstrate a line chart to show the relationship between battery decay and odometer. 
In this given situation I think a trend line will be very useful to indicate the slope.

**Comment by willdale** [comment]
I'm not sure what you mean by "trend line" that can't be achieved using a multi-line chart.

Can you clarify please?

**Comment by wyk111wyk** [comment]
Something like this![image](https://user-images.githubusercontent.com/8171481/112618267-ea123b00-8e60-11eb-94b6-c50a38f87ead.jpeg)

**Comment by willdale** [comment]
Linear trend line added in v2.2.0 

The View Modifier probably needs to placed quite near chart. 

```swift
.linearTrendLine(chartData: CTLineBarChartDataProtocol,
                 firstValue: Double,
                 lastValue: Double)
```

Thanks
