### ISSUE TITLE
Setting the minimum and maximum values for y-axis on line charts?

### ISSUE THREAD

**Issue by jeffgrann** [willdale/SwiftUICharts#4]
It seems that the y-axis values are automatically generated to fall within the minimum and maximum values in the data points.  Is it possible to set these values independently of the data?  Specifically, I'd like to set the minimum to zero.

**Comment by willdale** [comment]
If I understand the request, the new version (1.1.0) adds this functionality.

```swift
LineStyle(...,
          baseline: .zero)
```

**Comment by jeffgrann** [comment]
This did the trick. Thanks again. 😀
