### ISSUE TITLE
It is possible to add some sort of value modifiers for y-axis labels?

### ISSUE THREAD

**Issue by rsayfutdinov** [willdale/SwiftUICharts#40]
I would like to transform the y-axis labels from [0,...,5] to something like ["ok","good",...,"poor"].
Is this possible?

**Comment by willdale** [comment]
It's not currently possible as the labels are automatically generated. However, I could look to add it as an option as some point.

I can't give an ETA on when I can look at it but I'll add it to the ToDo.

**Comment by willdale** [comment]
Custom Y Axis Labels added in v2.2.0.

It's not quite what you asked for but is allows for text in the y axis labels.

```swift
LineChartStyle(...
               yAxisLabelType: .custom,
               ...)
```

```swift
LineChartData(...
               yAxisLabels: ["One", "Two", "Three"],
               ...)
```

Thanks

**Comment by rsayfutdinov** [comment]
🚀 Awesome! Thank you!
