### ISSUE TITLE
Customize dot and markerType

### ISSUE THREAD

**Issue by BulatMukhutdinov** [willdale/SwiftUICharts#43]
Please, provide an API to

customize markerType, especially color and stroke width.
customize DotStyle - ideally, accept view builder. At least change the way building dot. Now users could specify dot color and stroke. But it would be more flexible to set background color and radius and foreground color and radius.
Thanks

**Comment by willdale** [comment]
ViewBuilder for the Dot is something that would have to wait until version 3 as it would require breaking changes to the API.


---


```swift
DotStyle(size: 50,
         fillColour: .red,
         lineColour: .blue,
         lineWidth: 20)
```
![Simulator Screen Shot - iPhone 12 Pro - 2021-03-26 at 14 00 36](https://user-images.githubusercontent.com/63838770/112643031-d1dbf500-8e3b-11eb-9157-7a6dbb9fdae1.png)


---


```swift 
DotStyle(size: 50,
          fillColour: .red,
          lineColour: .blue,
          lineWidth: 4)
```

![2](https://user-images.githubusercontent.com/63838770/112643346-30a16e80-8e3c-11eb-85cd-d1d915d6e7d9.png)


---


Other than ViewBuilder, what other customisations would you like?

Thanks.

**Comment by BulatMukhutdinov** [comment]
I would like to draw a circle with a solid center and semi transparent borders
![image](https://user-images.githubusercontent.com/1418811/112712479-f50cb000-8ee0-11eb-8920-1f5c8a51bd35.png)

**Comment by willdale** [comment]
As of v2.2.0 this is now possible using:

## Dot

```swift
DotStyle(size: 20,
         fillColour: Color.blue,
         lineColour: Color.red.opacity(0.2),
         lineWidth: 4)
```

![3](https://user-images.githubusercontent.com/63838770/112715375-ba524a00-8ed7-11eb-8bd6-6cfd00bc5006.png)

## Marker

```swift
LineChartStyle(...
               markerType: .full(attachment: .line(dot: .style(DotStyle())), colour: .blue, style: StrokeStyle(lineWidth: 1)),
               ...)
```

Thanks

**Comment by BulatMukhutdinov** [comment]
Perfect, thank you!
