### ISSUE TITLE
FilledLineChart stroke

### ISSUE THREAD

**Issue by BulatMukhutdinov** [willdale/SwiftUICharts#47]
I am trying to draw FilledLineChart with a solid stroke on the top. 
Something like this
![image](https://user-images.githubusercontent.com/1418811/113019733-966a5f00-918a-11eb-8be1-ac2cc672798c.png)

Is it possible to do with your lib?

**Comment by willdale** [comment]
This has been added in v2.3.0. 

```swift
FilledLineChart(chartData: data)
                .filledTopLine(chartData: data,
                               lineColour: ColourStyle(colour: .red),
                               strokeStyle: StrokeStyle(lineWidth: 3))
```

![Simulator Screen Shot - iPhone 12 Pro - 2021-03-31 at 10 08 36](https://user-images.githubusercontent.com/63838770/113120079-1cc58600-9209-11eb-9490-c9f24451a76b.png)
