### ISSUE TITLE
Can't find ChartData or ChartDataPoint in scope on any branch

### ISSUE THREAD

**Issue by jhoughjr** [willdale/SwiftUICharts#50]
None of the examples will work as they will not build.
A closed issue indicated this was fixed but it is still broken.

**Comment by willdale** [comment]
I can't replicate the issue.

If it's looking for `ChartData` and `ChartDataPoint`, then it's an older version of the demo project.

Whats steps are you going through to get this issue?

**Comment by willdale** [comment]
I'll close this off but feel free to reopen it or open a new issue.
