### ISSUE TITLE
Y axis labels and legend pushed off view with large data no. of data points

### ISSUE THREAD

**Issue by kennedycraig** [willdale/SwiftUICharts#51]
I am experiencing the behavior that y axis labels are starting to be pushed outside the view as I increase the number of data points. 30 datapoints are fine but as I increase beyond 30, the labels begin to be pushed out. Have I hit a limit?
![labelmissing](https://user-images.githubusercontent.com/10380669/114593287-ec92d400-9c59-11eb-92c5-f66d58298cc2.jpg)

**Comment by willdale** [comment]
This seams to be an oversight on my part, it's to do with handling optionals in the X Axis Labels.

If you remove `.xAxisLabels` view modifier or set `LineChartStyle -> xAxisLabelsFrom` to `.chartData()` it should fix it. 

I'll push a proper fix out for it tomorrow.

**Comment by kennedycraig** [comment]
Yep. That nailed it. Thank you so much!

**Comment by willdale** [comment]
No worries, glad it's working.

**Comment by kennedycraig** [comment]
Hi, Will.
I should expect that xAxis labels _dont_ show when you use this workaround, correct?

**Comment by willdale** [comment]
Hi,

`.xAxisLabels` view modifier is needed to to show the labels.

If there are too many labels in the data points you can set `LineChartStyle -> xAxisLabelsFrom` to `.chartData()` to show the `LineChartData -> xAxisLabels` array with fewer labels.

The fix I'll look at tomorrow is for when data points don't have a value in `xAxisLabel`.

**Comment by kennedycraig** [comment]
Thank you again. I was trying to model the case where large numbers of points - lets say 90 (representing 90 days) only had 3 x-axis labels(say the month beginning.). I love your work.

**Comment by willdale** [comment]
Hi Craig,

Is everything working for you?

Any change I might make the way the labels are laid out, breaks potential implementations that people are using.

Thanks

**Comment by kennedycraig** [comment]
Hi, Will.
It works with the .chartdata() modifier. I dont mind if you break something - I am not yet in production and very willing to work around anything to help you/the effort improve if needed. Its very promising work.
Craig

**Comment by willdale** [comment]
Ah indeed, it is not working. I'll work on a fix.

If all the rest is working,  I will leave it as is.

Thanks

**Comment by kennedycraig** [comment]
Cheers. Let me know when I can pull it and I will give it a shot.

**Comment by kennedycraig** [comment]
Hi, Will.
I rebuilt with 2.3.1 this morning. All looks good xAxisLabels rotation working as expected. I really appreciate it - the work looks beautiful in my product.
Craig

**Comment by willdale** [comment]
Glad its all working! v2.3.1 introduced a layout bug with when rotation was 0. Latest version is now v2.3.2.

Thank you for your support!

Will
