### ISSUE TITLE
Suggestion/Request - Pie Chart values < 0

### ISSUE THREAD

**Issue by kennedycraig** [willdale/SwiftUICharts#53]
When pie charts are fed values < 0 (e.g. decimals representing % summing to 1.0) the touch info box value is rounded to an int 0. Fixed by just multiplying by 100 in the case of a percentage in the view code. 

Would be nice to be able to: 1) Feed in a specifier to allow for formatting of the info box number in the intended format.

Unrelated - would be nice to be able to label the slices in a way that did not require touch to display the slice value.

Food for thought.

**Comment by willdale** [comment]
# Decimal
 Decimal precision is possible currently.

```swift
PieChart(chartData: data)
    .touchOverlay(chartData: data, specifier: "%.01f")
```
```swift
PieDataSet(dataPoints: [
            PieChartDataPoint(value: 0.7, description: "One",   colour: .blue),
            PieChartDataPoint(value: 0.2, description: "Two",   colour: .red),
            PieChartDataPoint(value: 0.9, description: "Three", colour: .purple),
            PieChartDataPoint(value: 0.6, description: "Four",  colour: .green),
            PieChartDataPoint(value: 0.4, description: "Five",  colour: .orange)],
           legendTitle: "Data")
```
![Decimal precision in pie chart](https://user-images.githubusercontent.com/63838770/115010750-b0ec4a00-9ea5-11eb-9d64-aed55e697efe.png)

---

# Segment Labels

I've add this to a "To Do" project.

**Comment by kennedycraig** [comment]
Thanks, Will.

**Comment by willdale** [comment]
No worries.

**Comment by willdale** [comment]
This has been added in v2.5.0.

```swift
 PieChartDataPoint(value: 7, description: "One", colour: .blue, label: .icon(systemName: "1.square", colour: .white, size: 30))
```

Thanks,
Will

**Comment by kennedycraig** [comment]
Perfectly brilliant! Thanks, Will!
