### ISSUE TITLE
Wrong Y Label in StackedBarChart

### ISSUE THREAD

**Issue by ataias** [willdale/SwiftUICharts#54]
# Context
While using the library in my app, I noticed the Y Labels were odd. I investigated the demo add to see if I could reproduce the error and I noticed the following in `StackedBarChartDemoView.swift`:

For a given `MultiBarDataSet`, we can see the labels for each point just fine, but the overall Y Label has a wrong value. For instance, look at this code:
```swift
MultiBarDataSet(dataPoints: [
    MultiBarChartDataPoint(value: 100, description: "Q1 Sales", group: Group.england.data),
    MultiBarChartDataPoint(value: 500, description: "Q1 Sales", group: Group.scotland.data),
    MultiBarChartDataPoint(value: 300, description: "Q1 Sales", group: Group.wales.data),
], setTitle: "Q1"),
```

When I select the labels, I can see 100, 500 and 300 just fine:

![image](https://user-images.githubusercontent.com/1009034/115110442-d3d43800-9f51-11eb-9855-c5c5cfc4a1e9.png)

But notice that if we sum 100 + 500 + 300, we get 900 for Q1, which does not match the chart above. For Q4, we should sum 400 + 800 + 200 = 1400, which definitely does not match the max Y Label of 800 there.

FWIW I reviewed wikipedia for [Bar Charts](https://en.wikipedia.org/wiki/Bar_chart) and a [random article](https://chartio.com/learn/charts/stacked-bar-chart-complete-guide/) to see if I was misunderstanding what a stacked bar chart should do, but I think I am understanding it correctly.

# Metadata
This was on the demo repo on commit 75b2b878ad908b706eb8d6c10a8ecd7cef667af5 from Wed Mar 31 09:55:27 2021 +0100. I had commented a line with `topLine: .maximum(of: 900)`, but you can see the same behaviour with this line enabled too.

**Comment by ataias** [comment]
@willdale I submitted a PR that I hope to fix this issue: https://github.com/willdale/SwiftUICharts/pull/55 . Could you take a look and let me know your thoughts?

**Comment by willdale** [comment]
I've added a comment under the PR #55. Let's continue the conversation there.
