### ISSUE TITLE
FilledLineChart inside of a NavigationView using .averageLine 

### ISSUE THREAD

**Issue by oalansari82** [willdale/SwiftUICharts#57]
Hi There, 

I just wanted to say this is the best SwiftUI Chart module I've used so far. Thanks for sharing. 

I am using a FilledLineChart which is wrapped inside of a navigationView. Once I use the .averageLine. The whole view starts animating from top left corner when it appears the first time. I am not sure if I made any sense but the video attached shows the behavior. 

https://user-images.githubusercontent.com/19424804/115284837-d99a6b00-a155-11eb-96e5-d7ed5fe70dc8.mov

```swift
FilledLineChart(chartData: chartData)
                                .touchOverlay(chartData: chartData, specifier: "%.0f")
                                .averageLine(chartData: chartData,strokeStyle: StrokeStyle(lineWidth: 1, dash: [5,10]))
                                .yAxisGrid(chartData: chartData)
                                .yAxisLabels(chartData: chartData)
                                .infoBox(chartData: chartData)
                                .floatingInfoBox(chartData: chartData)
                                .headerBox(chartData: chartData)
                                .legends(chartData: chartData, columns: [GridItem(.flexible()), GridItem(.flexible())])
                                .frame(minWidth: 150, maxWidth: 900, minHeight: 350, idealHeight: 350, maxHeight: 400, alignment: .center)
                                .padding()
```

**Comment by willdale** [comment]
Hi Omar,

It's interesting, I can't replicate the issue. What version of the package are you running?

https://user-images.githubusercontent.com/63838770/115368703-3f6f0d00-a1bf-11eb-8257-e2d673ebab12.mov

```swift
struct TabViewView: View {
    
    var body: some View {
        TabView {
            NavigationView {
                Text("Hello")
                    .navigationTitle(Text("Home"))
            }
            .tabItem {
                Label("Main", systemImage: "house")
            }
            NavigationView {
                OalansariFilledLineChartTest()
                    .navigationTitle(Text("Chart"))
            }
            .tabItem {
                Label("Chart", systemImage: "chart.bar")
            }
        }
    }
}
```

**Comment by oalansari82** [comment]
Hi Willdale

I am running 2.3.2 and here is the complete link to the file. The whole project is also there just in case you wanted to look around. I am a beginner so please ignore my sluggish coding standards. 

https://github.com/oalansari82/COVID-Qatar/blob/main/COVID%20Qatar/Views/ChartView.swift

**Comment by willdale** [comment]
Hi @oalansari82,

Nice looking app, good work. 

This was an interesting bug but `v2.4.1` should fix the issue you were having.

---

A couple of suggestions for your `ChartView`:

There are some layout issues where the chart package isn't reacting to width changes in the y axis labels. This means that info box and and average marker are offset.

Should be a simple fix: add `.id(chartData.id)` after ` .legends`

### BUT

As `updateUI()` is in `.onAppear` this causes a layout loop where the view change, which fires `.onAppear`, which updates the view, which fires `.onAppear` .............

### Solution

Add: 
```swift
@State private var hasAppeared: Bool = false
```
and change
```swift
.onAppear {
    if !hasAppeared {
        updateUI()
        hasAppeared = true
    }
}
```

### OR

Find a way to move `updateUI()` out of `.onAppear` as it may fire multiple times.

---

Let me know if this has has fixed it for you.

Thanks
Will

**Comment by oalansari82** [comment]
Hey Will, 

It would've not looked good without this great package.

v2.4.1 has fixed the issue and thank you for the suggestion. I was wondering why was it looping through and I had to remove the `.id(chartData.id)`
