### ISSUE TITLE
Top of bar charts have deformation

### ISSUE THREAD

**Issue by vrwim** [willdale/SwiftUICharts#58]
Because the corner radius is set before the stretching is applied, longer bars have more corner radius than shorter bars.

Not sure how to approach this, maybe stretch first, then apply the corner radius (if I tried this, I didn't get any rectangle). Other approach might be to apply a different corner radius for x and y, and not use a circle to make the corner, but use an ellipse?

Screenshot attached for clarity:

![IMG_D14A82E2258D-1](https://user-images.githubusercontent.com/1311717/115702187-e9d66400-a368-11eb-9c6d-6016e22feae0.jpeg)

**Comment by willdale** [comment]
Hi @vrwim,

Tried a few different things during development, they all suffered from the same issue. Using ellipse had the same behaviour.

I'll have another a look at it.

Thanks

**Comment by willdale** [comment]
Hi @vrwim,

I couldn't get it to work without deformation, have you got any ideas for it?

**Comment by funkenstrahlen** [comment]
I can confirm this bug.

**Comment by funkenstrahlen** [comment]
Very happy to hear that we might have a solution for this now!
