### ISSUE TITLE
Set maximum baseline value.

### ISSUE THREAD

**Issue by jeffgrann** [willdale/SwiftUICharts#6]
I'd like to be able to set a maximum value for the baseline while computing the minimum value from the data points.

For example, if I set the maximum baseline value to 200, the baseline would be:

200 with data points of [250.0, 245.0, 238.0]

190 with data points of [250.0, 245.0, 238.0, 190.0]

Something like this:

```
enum Baseline {
    case minimum
    case minimumWithMaximum(of: Double) // New enum case
    case zero
}

var baseline: Baseline
var data = [250.0, 245.0, 238.0]
var minValue: Double

baseline = .minimumWithMaximum(of: 200)

switch baseline {
case .minimum:
minValue = data.min() ?? 0

case .minimumWithMaximum(let maximum):
    minValue = min(data.min() ?? 0, maximum)
    
case .zero:
    minValue = 0
}

print(minValue)
```

This would print 200.0.

Changing var data = [250.0, 245.0, 238.0] to var data = [250.0, 245.0, 238.0, 190.0] would print 190.0

**Comment by willdale** [comment]
![Screenshot 2021-02-03 at 20 47 24](https://user-images.githubusercontent.com/63838770/106807613-3dd28600-6661-11eb-97ec-f969cc999219.png)

It's interesting, I can't get a case with an associated value to be selectable outside of the library.

![Screenshot 2021-02-03 at 20 47 54](https://user-images.githubusercontent.com/63838770/106807661-4cb93880-6661-11eb-9c96-5cd2bcb96274.png)

 Internally it works as expected.

![Screenshot 2021-02-03 at 20 48 27](https://user-images.githubusercontent.com/63838770/106807819-7ffbc780-6661-11eb-8681-74a035481421.png)

I might have to add another property to the ListStyle struct. 

```
LineStyle(baseline: .minimumWithMaximum,
          baselineValue: 200)
```
Thoughts?

**Comment by willdale** [comment]
It seams it was a matter of scope. New version 1.1.1 adds new case to Baseline Enum.

```swift
case minimumWithMaximum(of: Double)
```

Thank you for your suggestions.

**Comment by jeffgrann** [comment]
Tried it out and it works great. Thanks again!

**Comment by willdale** [comment]
No worries!
