### ISSUE TITLE
using xAxisLabelsFrom : .chartData(rotation: .degrees(0))  will mess with the Y axis labels position

### ISSUE THREAD

**Issue by jotaj91** [willdale/SwiftUICharts#61]
I think the problem is in YAxisLabelCell.swift

`
    .onAppear {
        chartData.viewData.xAxisLabelHeights.append(width)
    }
`
changing width to height solved the problem for me.

**Comment by willdale** [comment]
I've been having problems with the rotation since I first implemented it.

I'm currently looking to overhaul it.

**Comment by kennedycraig** [comment]
Confirmed same issue with rotation 90. This is working in 2.3, Xcode 12.4, seems to have become an issue somewhere in 2.5, with Xcode 12.5

**Comment by willdale** [comment]
Hopefully v2.6 has fixed this. 🙏 

If not feel free to reopen this.

**Comment by kunalverma25** [comment]
@willdale This issue is still present..
Because of this line -
`
chartData.viewData.xAxisLabelHeights.append(geo.frame(in: .local).width)
`
Changing width to height solves this.
