### ISSUE TITLE
Build inline docstrings into docs website

### ISSUE THREAD

**Issue by joelberkeley** [willdale/SwiftUICharts#63]
Much of this library has docstrings. It would be nice to be able to see those presented nicely in a docs website.

The actual publishing of that website for new versions of the library (using e.g. GitHub actions) can be a different piece of work

**Comment by joelberkeley** [comment]
@willdale what did you say the standard swift library for building docstrings into a website was?

**Comment by willdale** [comment]
@joelberkeley, I think the go to library from automatic documentation generation is `Jazzy`. [https://github.com/realm/jazzy](https://github.com/realm/jazzy)

Here's an example of the output from `fullWidth`: [https://reduxkit.github.io/ReduxKit/](https://reduxkit.github.io/ReduxKit/).

At it's most basic, to generate docs you would use the command: `jazzy --min-acl public --theme fullwidth`

**Comment by joelberkeley** [comment]
how about a "docs" directory with configuration and instructions to build the docs locally? you could base the github actions on that

**Comment by willdale** [comment]
That sounds good, trigger a GitHub Action on `release`.

What would need to be in the docs folder to start this up, or, would it all be added through an action?

**Comment by willdale** [comment]
Thank you @joelberkeley for your assistance in setting this up.
