### ISSUE TITLE
MultiLine Chart floating box blocks view

### ISSUE THREAD

**Issue by srijaljoshi** [willdale/SwiftUICharts#65]
I'm trying to get the floating box to be transparent so that it doesn't block the graph. How can I achieve this? 

![Picture](https://user-images.githubusercontent.com/25680098/117079748-0330c600-ad02-11eb-85d3-184d78629250.png)

**Comment by willdale** [comment]
In `MultiLineChartData`:

```swift
LineChartStyle(...
               infoBoxBackgroundColour: Color.clear,
               ...
```

**Comment by srijaljoshi** [comment]
That works. Thanks!
