### ISSUE TITLE
X Axis labels overlapping

### ISSUE THREAD

**Issue by srijaljoshi** [willdale/SwiftUICharts#66]
What would be the best solution to fit everything? The data I'm using has 12 data points with time increment of 5 mins. Is there a way to tilt the labels or use only a few labels out of the 12 spread out in the x-axis?

![xAxisLables](https://user-images.githubusercontent.com/25680098/117080030-9d910980-ad02-11eb-97d2-937fb41d60b2.png)

**Comment by willdale** [comment]
In `MultiLineChartData`:

```swift
LineChartStyle(...
               xAxisLabelsFrom: .dataPoint(rotation: .degrees(90)), 
               ...
```

in an update hopefully soon there is an overhaul of label rotation.

OR

In `ChartData`:

```swift
MultiLineChartData(...
                   xAxisLabels: ["January", "December"],
                   chartStyle: LineChartStyle(...
                                              xAxisLabelsFrom: .chartData(rotation: .degrees(0)), 
                                              ...
                   ...
```

**Comment by srijaljoshi** [comment]
Thanks. That really helped.
Is there a way to sample a few x-axis labels and display them when there are like 100+ points?

**Comment by willdale** [comment]
The library doesn't do any of the filtering, that needs to be done before. However if only some data points have `xAxisLabels` then the library will still place the others in the right position.
