### ISSUE TITLE
Combined bar and line chart

### ISSUE THREAD

**Issue by colinhumber** [willdale/SwiftUICharts#67]
Working with 2 data sets that should be displayed with a bar chart the grouped chart is perfect. Is it possible with the current setup to display a bar chart with a line chart overlaid?

**Comment by willdale** [comment]
This is something I want to implement when I have time.

**Comment by willdale** [comment]
In v2.6 there is a slightly experimental new view modifier.

---

```swift
BarChart(chartData: data)
    .extraLine(chartData: data, legendTitle: "Test") {
        extraLineData
    } style: {
        extraLineStyle
    }
```
```swift
private var extraLineData: [ExtraLineDataPoint] {
    [ExtraLineDataPoint(value: 1),
     ExtraLineDataPoint(value: 4),
     ExtraLineDataPoint(value: 9),
     ExtraLineDataPoint(value: 4),
     ExtraLineDataPoint(value: 6),
     ExtraLineDataPoint(value: 5),
     ExtraLineDataPoint(value: 6)]
}
private var extraLineStyle: ExtraLineStyle {
    ExtraLineStyle(lineColour: ColourStyle(colour: .blue),
        lineType: .curvedLine,
        lineSpacing: .bar,
        yAxisTitle: "Bob",
        yAxisNumberOfLabels: 7,
        animationType: .raise,
        baseline: .zero)
}
```

---

![bar and line](https://user-images.githubusercontent.com/63838770/117651706-2936ea00-b18a-11eb-8a70-ea4b2ffd77eb.png)

---

It's currently undocumented, just ask if you need help.

Thanks,
Will
