### ISSUE TITLE
Custom Legend for Bar Charts

### ISSUE THREAD

**Issue by tfeige91** [willdale/SwiftUICharts#70]
Is it possible to draw a custom Legend for a bar chart? 
I have many bars but only two conditions and want to place only those two conditions in a legend below the chart. 
What I get is a Legend with one Item for each bar.

In the [Docs](https://willdale.github.io/SwiftUICharts/Classes/BarChartData.html) it says that legends is part of BarChartData but I can't add id there.

**Comment by willdale** [comment]
Custom legends are not possible. They get generated based on the data provided.

 You could look at Grouped Bar Charts? [https://github.com/willdale/SwiftUICharts#grouped-bar-chart](https://github.com/willdale/SwiftUICharts#grouped-bar-chart)

**Comment by tfeige91** [comment]
Setting up a Grouped Bar Chart with only one group did the trick :) 
Thanks!

**Comment by willdale** [comment]
No worries, glad it's working.
