### ISSUE TITLE
Possible bug in Series 3 Watches? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#73]
I am seeing a crash on Apple Watch that seems to be limited to Series 3 (all running Watch OS 7) or higher.  I can't tell what the cause is but it seems to be related to the metaData in SwiftUICharts, any ideas? 🤔

![image](https://user-images.githubusercontent.com/9816100/117678654-97c17b00-b17d-11eb-8892-bd1156d60b1e.png)

**Comment by willdale** [comment]
hmmmm, do you have any repeatable code? I can't get it to crash in the simulator.

**Comment by gesabo** [comment]
@willdale  i wasn't able to repeat in the simulator either.  I am trying to disable Dead Code Stripping for WatchOS as I've read this caused some weird crashes with Series 3 Watches.  This may not be related to SwiftUICharts, but did seem to occur when I started using on the watch.  I will report back if the crashes stop.

**Comment by gesabo** [comment]
update that removing Dead Code Stripping on WatchOS seems to have fixed this crash.
