### ISSUE TITLE
Rotation on Line Chart with large no points, causes y axis to shift off page

### ISSUE THREAD

**Issue by kennedycraig** [willdale/SwiftUICharts#76]
Sorry, Will. Reopening. Updated to 2.6.1

Using, xAxisLabelsFrom     : .chartData(rotation: .degrees(90)), still forces y axis off screen.
Using, xAxisLabelsFrom     :.chartData(), causes labels to disappear.
See two images below.
Let me know how I can be of help.

![image](https://user-images.githubusercontent.com/10380669/117700476-0f9aa000-b194-11eb-89b9-ba85c8d0d73b.png)
![image](https://user-images.githubusercontent.com/10380669/117700678-538da500-b194-11eb-810b-851f469148a4.png)

**Comment by willdale** [comment]
just checking: when you set `xAxisLabelsFrom : .chartData()` are you feeding in and array of strings to the ChartData `xAxisLabels: ["String", "String"]`?

![test](https://user-images.githubusercontent.com/63838770/117702426-64eca680-b1c0-11eb-860d-396347de5f00.png)

**Comment by willdale** [comment]
maybe v2.6.3 has fixed it

**Comment by kennedycraig** [comment]
no, .chartdata(rotation: ...)

Do you want me to rework with .datapoints and try?

**Comment by kennedycraig** [comment]
VICTORY!!!

![image](https://user-images.githubusercontent.com/10380669/117837364-63b28c80-b247-11eb-8122-ad1894df2660.png)
