### ISSUE TITLE
Customize blank caption

### ISSUE THREAD

**Issue by wyk111wyk** [willdale/SwiftUICharts#77]
So far the blank caption is "No Data" for table chart, can you make it customizable, so we can localize this hint. 
![截屏2021-05-18 上午11 09 10](https://user-images.githubusercontent.com/8171481/118584751-2cedf080-b7ca-11eb-9d3a-313219af365b.png)

**Comment by willdale** [comment]
It is customisable.

```swift
LineChartData(...,
              noDataText: Text("Hello World."))
```

**Comment by wyk111wyk** [comment]
Thx for your response, this is great, but I have another question: Is the width between two nodes customizable?
![IMG_7232](https://user-images.githubusercontent.com/8171481/118765224-5895d700-b8ad-11eb-9228-6a46c6fe67f1.jpg)

**Comment by willdale** [comment]
No, what you could do is,  not provide a label for every other data point;

```swift
LineChartDataPoint(value: 12000, xAxisLabel: "1"),
LineChartDataPoint(value: 10000),
LineChartDataPoint(value: 8000, xAxisLabel: "3"),
LineChartDataPoint(value: 17500),
...
```
