### ISSUE TITLE
No such module 'SwiftUICharts'

### ISSUE THREAD

**Issue by wisepmlin** [willdale/SwiftUICharts#82]
The package has been added, still this prompt when importing

**Comment by willdale** [comment]
Hi,

In `Project -> General -> Targets -> Frameworks, Libraries and Embedded Content`, make sure that it has been added to the list.

![Screenshot 2021-05-29 at 07 35 39](https://user-images.githubusercontent.com/63838770/120060581-7e12a580-c050-11eb-80fe-c48d5dee5df6.png)

If that doesn't work, `File -> Swift Packages -> Reset Packages Caches` && `Resolve Package Versions`

![Screenshot 2021-05-29 at 07 36 25](https://user-images.githubusercontent.com/63838770/120060656-e6fa1d80-c050-11eb-8964-bd2c4be0fb3f.png)
