### ISSUE TITLE
Use Doubles for xAxis labels?

### ISSUE THREAD

**Issue by 7elysium** [willdale/SwiftUICharts#83]
I'm trying to create a multi-line chart. The data I have is of [number, number] type rather than [number, string]. Is there any way I can change the default type that is used for the xAxis labels?

Thank you!
(I'm very new to programming! I'm sorry if this has a very easy fix!)

**Comment by willdale** [comment]
Hi,

For the numeric value you want to use as a string you can use String Interpolation: 

```swift
xAxisLabel: "\(2)"
```

or initialise a new string using the numeric value.

```swift
xAxisLabel: String(2)
```
---
Will

**Comment by 7elysium** [comment]
Got it!Thank you so much!
