### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by estebanpadilla** [willdale/SwiftUICharts#88]
Hello, first of all, awesome library. Thanks so much.

Now, I wonder if iOS 13 can be supported, is that a question that you can help me with?

Greetings.

**Comment by willdale** [comment]
Hi, thanks.

When I set to target iOS 13, it returns ~80 errors. Many of them are to do with accessibility as the API changed between 13 and 14. There are other ones such as font type and grid items.

None of them are insurmountable, however, I won't have time to add in the relevant preprocessor directives to add backward compatible support.

From iOS 15, this library will support `at least` current and current - 1. 

Thanks,
Will
