### ISSUE TITLE
TouchOverlay breaks LineStyle with ignoreZero flag

### ISSUE THREAD

**Issue by krin-san** [willdale/SwiftUICharts#90]
I wanted to draw a time-based graph which always has 24 points. For that I'm filling out missing points (from current time till the rest of the day) with zeroes and set `LineStyle.ignoreZero: true`. Unexpectedly for me, when inspecting graph data with TouchOverlay and FloatingInfoBox modifiers and hovering over zero points, selection marker jumps down to zero and graph starts drawing both line and dots on Y-level 0.

I expected TouchOverlay to respect `ignoreZero` value and not drawing a marker on the line if it goes to ignored 0 points.

<img width="345" alt="Screenshot 2021-06-11 at 09 25 49" src="https://user-images.githubusercontent.com/2318002/121649193-9e068800-ca98-11eb-93ff-9974edd525b0.png">

<details><summary>Demo videos</summary><p>

https://user-images.githubusercontent.com/2318002/121649194-9e9f1e80-ca98-11eb-91e1-2b7f4cefcf93.mov

https://user-images.githubusercontent.com/2318002/121649201-a068e200-ca98-11eb-8576-9f1b623388ce.mov

</p></details>

**Comment by willdale** [comment]
I'll have a look.
