### ISSUE TITLE
Localization for chart labels and titles

### ISSUE THREAD

**Issue by LJNIC** [willdale/SwiftUICharts#96]
Currently the `Text` labels don't support localization. It should be as easy as wrapping all of the labels with `LocalizedStringKey(label)`.

**Comment by willdale** [comment]
I'll have a look.

Thanks,
Will

**Comment by willdale** [comment]
Hi @LJNIC, localisation support has been added in v2.8.2.

See bottom docs for some Additional tags to include in localization to support VoiceOver.

Thanks,
Will

**Comment by LJNIC** [comment]
Thanks again!

**Comment by AakashGeidea** [comment]
Hi @willdale, 

Localisation isn't support to axis values? My app is in multi languages and how to set values on axis based on language? It is supporting or not? Please guide.
