### ISSUE TITLE
Trouble building in Xcode 13? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#98]
@willdale have you tried building in Xcode 13 yet?  Having trouble building a project with SwiftUICharts in it, and it seems to be having issues with `GroupedBarChart` -  `The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

**Comment by willdale** [comment]
I did have some issues, they are fixes in v2.8.1. 

Thanks,
Will
